import numpy as np
import matplotlib.pyplot as plt
def horizontalni_hitac(v0, kut, x0, y0, dt):
    v_x=list()
    v_x.append(np.cos(np.radians(kut))*v0)
    v_y=list()
    v_y.append(np.sin(np.radians(kut))*v0)
    x=list()
    x.append(x0)
    y=list()
    y.append(y0)
    a_y=list()
    a_y.append(-9.81)
    a_x=list()
    a_x.append(0)
    t=list()
    t.append(0)
    for i in np.arange(0, 10, dt):
        t.append(t[-1]+dt)
        x.append(x[-1]+v_x[-1]*dt)
        y.append(y[-1]+v_y[-1]*dt)
        v_x.append(v_x[-1]+a_x[-1]*dt)
        v_y.append(v_y[-1]+a_y[-1]*dt)
        a_y.append(-9.81)
        a_x.append(0)
    plt.plot(x, y)
    plt.xlabel("pomak x [m]")
    plt.ylabel("pomak y [m]")
    plt.show()
    plt.plot(t, y)
    plt.xlabel("vrijeme [m/s]")
    plt.ylabel("pomak y [m]")
    plt.show()
    plt.plot(t, x)
    plt.xlabel("vrijeme [m/s]")
    plt.ylabel("pomak x [m]")
    plt.show()


print(np.cos(np.radians(90)))   #nije nula, pa garf za kut 90 ispada krivo 
horizontalni_hitac(200, 50, 0, 0, 0.01)
